trigger:
- main

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'ubuntu-latest'
#     mac:
#       operatingSystem: 'macos-latest'
#     windows: 
#       operatingSystem: 'windows-latest'  

# This wil be automatically select the OS
pool:
  vmImage: 'ubuntu-latest' #$(operatingSystem)

stages:
- stage: Build
  jobs: 
  - job: BuildJob
    steps:
    - bash: echo "Do the Build!"

- stage: DevDeploy
  jobs: 
  - deployment: DevDeployJob
    environment: Dev
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to Dev

- stage: QADeploy
  jobs: 
  - deployment: QADeployJob
    environment: QA
    strategy:
     runOnce:
       deploy:
         steps:
           - script: echo deploy to QA



