trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publicKey
  inputs:
    secureFile: 'azure_rsa.pub'

- script: |
    # Install jq for JSON parsing
    sudo apt-get update && sudo apt-get install -y jq
    
    # Get latest Terraform version from HashiCorp releases JSON
    LATEST=$(curl -s https://releases.hashicorp.com/terraform/index.json | jq -r '.versions | keys[]' | sort -Vr | head -n1)
    echo "Latest Terraform version: $LATEST"
    
    # Download latest Linux amd64 zip
    curl -fsSL https://releases.hashicorp.com/terraform/${LATEST}/terraform_${LATEST}_linux_amd64.zip -o terraform.zip
    
    # Unzip and move to /usr/local/bin
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    
    # Verify installation
    terraform version
  displayName: 'Install Latest Terraform'



# Initialization phase
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publicKey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-management-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountskety'
    backendAzureRmContainerName: 'storageaccountsketycontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true

# Apply phase
- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-management-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publicKey.secureFilePath)'
    allowTelemetryCollection: true
    